server:
  port: 9090

spring:
  application:
    name: cloud-payment-service
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource            # 当前数据源操作类型
    driver-class-name: org.gjt.mm.mysql.Driver              # mysql驱动包 com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/spark?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: root
    druid:
      test-while-idle: false
  main:
    allow-circular-references: true

mybatis:
  mapper-locations: classpath:mapper/*.xml, classpath:mapper/user/*.xml, classpath:mapper/music/*.xml
#  type-aliases-package: com.spark.springcloud.entities    # 所有Entity别名类所在包

# 日志配置
logging:
  level:
    com: debug

